# Development configuration for Medtech RAG solution

app:
  name: "Medtech RAG"
  version: "0.1.0"
  environment: "development"
  debug: true

api:
  host: "0.0.0.0"
  port: 8000
  cors:
    origins:
      - "http://localhost:3000"
      - "http://localhost:8000"
    allow_credentials: true
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["*"]

storage:
  containers:
    raw_documents: "raw-documents"
    processed_documents: "processed-documents"
    embeddings: "embeddings"
  max_file_size_mb: 50
  allowed_extensions:
    - ".pdf"
    - ".json"
    - ".txt"
    - ".md"

search:
  index_name: "medtech-documents"
  api_version: "2023-11-01"
  scoring_profile: "default"
  max_results: 50
  highlight_fields:
    - "content"
    - "title"
  facets:
    - "authors"
    - "publication_year"
    - "document_type"

document_intelligence:
  api_version: "2023-07-31"
  model_id: "prebuilt-layout"
  medical_focus: true
  extract_tables: true
  extract_figures: true
  confidence_threshold: 0.85
  features:
    - "tables"
    - "keyValuePairs"
    - "entities"
    - "figures"

embeddings:
  model_name: "pritamdeka/S-PubMedBert-MS-MARCO"
  dimension: 768
  batch_size: 16
  max_length: 350
  medical_optimized: true
  pooling: "mean"
  normalize: true

chunking:
  strategy: "contextual_medical"
  base_chunk_size: 300
  chunk_overlap: 50
  min_chunk_size: 100
  preserve_medical_sections: true
  context_tokens: 75
  separators:
    - "\n## "      # Medical section headers
    - "\n### "     # Medical subsection headers
    - "\n\n"       # Paragraph breaks
    - "[TABLE_END]" # End of tables
    - "[SECTION_END:" # End of sections
    - "\n"
    - ". "
    - " "

contextual_retrieval:
  enabled: true
  context_model: "claude-3-haiku-20240307"
  context_length: 75
  hybrid_search: true
  medical_context: true

retrieval:
  top_k: 10
  rerank_top_k: 5
  hybrid_alpha: 0.5  # 0 = keyword only, 1 = semantic only
  min_relevance_score: 0.7

logging:
  level: "INFO"
  format: "json"
  file:
    enabled: true
    path: "logs/medtech-rag.log"
    max_size_mb: 10
    backup_count: 5